alarm_control_panel:
  platform: alarmdotcom
  scan_interval: 10
  username: !secret alarmdotcom_username
  password: !secret alarmdotcom_password

automation:
  - alias: Alarm System - Notify If Alarm Not Set When Nobody Is Home
    trigger:
      - platform: zone
        entity_id: device_tracker.lauras_iphone
        zone: zone.home
        event: leave
      - platform: zone
        entity_id: device_tracker.michael_michaelgalaxys10_2
        zone: zone.home
        event: leave
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ not is_state('device_tracker.lauras_iphone','home') }}"
        - condition: template
          value_template: "{{ not is_state('device_tracker.michael_michaelgalaxys10_2','home') }}"
        - condition: state
          entity_id: alarm_control_panel.alarm_com
          state: 'disarmed'
    action:
      - service: notify.pushbullet #notify Michael
        data:
          message: The house alarm was not set.
      - service: notify.notify # notify Laura
        data:
          message: The house alarm was not set.
          
  - alias: Alarm System - Turn Off House When Alarm Is Set
    trigger:
      platform: state
      entity_id: alarm_control_panel.alarm_com
      from: 'disarmed'
      to: 'armed_away'
    action:
      - service: light.turn_off #lights
        data_template: 
          entity_id: "{{ states.light | map(attribute='entity_id') | list | join(', ') }}"
      - service: script.aircon_turn_off #aircon
      - service: media_player.turn_off #tv & speakers
        entity_id:
          - media_player.theatre_room_tv 
          - media_player.all_rooms
        
sensor:
  - platform: template
    scan_interval: 10
    sensors:
      front_door: #front door open/closed sensor
        friendly_name: "Front Door"
        value_template: >-
          {% if state_attr('alarm_control_panel.alarm_com', 'sensor_status')|regex_search('Front Door is Open', ignorecase=TRUE) %}
            Open
          {% else %}
            Closed
          {% endif %}
      motion_sensor_living: #living room motion sensor
        friendly_name: "Living Room Motion"
        value_template: >-
          {% if state_attr('alarm_control_panel.alarm_com', 'sensor_status')|regex_search('Living Sensor is Activated', ignorecase=TRUE) %}
            Active
          {% else %}
            Inactive
          {% endif %}
      motion_sensor_master_bedroom: #master bedroom motion sensor
        friendly_name: "Master Bedroom Motion"
        value_template: >-
          {% if state_attr('alarm_control_panel.alarm_com', 'sensor_status')|regex_search('Master Bedroom Sensor is Activated', ignorecase=TRUE) %}
            Active
          {% else %}
            Inactive
          {% endif %}
      motion_sensor_entry_hall: #entry hall motion sensor
        friendly_name: "Entry Hall Motion"
        value_template: >-
          {% if state_attr('alarm_control_panel.alarm_com', 'sensor_status')|regex_search('Entry Sensor is Open', ignorecase=TRUE) %}
            Active
          {% else %}
            Inactive
          {% endif %}
