frontend:
  themes: 
    midnight:
      # Main colors
      primary-color: '#5294E2'                                                        # Header
      accent-color: '#E45E65'                                                         # Accent color
      dark-primary-color: 'var(--accent-color)'                                       # Hyperlinks
      light-primary-color: 'var(--accent-color)'                                      # Horizontal line in about

      # Text colors
      primary-text-color: '#FFFFFF'                                                   # Primary text colour, here is referencing dark-primary-color
      text-primary-color: 'var(--primary-text-color)'                                 # Primary text colour
      secondary-text-color: '#5294E2'                                                 # For secondary titles in more info boxes etc.
      disabled-text-color: '#7F848E'                                                  # Disabled text colour
      label-badge-border-color: 'green'                                               # Label badge border, just a reference value

      # Background colors
      primary-background-color: '#383C45'                                             # Settings background
      secondary-background-color: '#383C45'                                           # Main card UI background
      divider-color: 'rgba(0, 0, 0, .12)'                                             # Divider

      # Table rows
      table-row-background-color: '#353840'                                           # Table row
      table-row-alternative-background-color: '#3E424B'                               # Table row alternative

      # Nav Menu
      paper-listbox-color: 'var(--primary-color)'                                     # Navigation menu selection hoover
      paper-listbox-background-color: '#2E333A'                                       # Navigation menu background
      paper-grey-50: 'var(--primary-text-color)'
      paper-grey-200: '#414A59'                                                       # Navigation menu selection

      # Paper card
      paper-card-header-color: 'var(--accent-color)'                                  # Card header text colour
      paper-card-background-color: '#434954'                                          # Card background colour
      paper-dialog-background-color: '#434954'                                        # Card dialog background colour
      paper-item-icon-color: 'var(--primary-text-color)'                              # Icon color
      paper-item-icon-active-color: '#F9C536'                                         # Icon color active
      paper-item-icon_-_color: 'green'
      paper-item-selected_-_background-color: '#434954'                               # Popup item select
      paper-tabs-selection-bar-color: 'green'

      # Labels
      label-badge-red: 'var(--accent-color)'                                          # References the brand colour label badge border
      label-badge-text-color: 'var(--primary-text-color)'                             # Now same as label badge border but that's a matter of taste
      label-badge-background-color: '#2E333A'                                         # Same, but can also be set to transparent here

      # Switches
      paper-toggle-button-checked-button-color: 'var(--accent-color)'
      paper-toggle-button-checked-bar-color: 'var(--accent-color)'
      paper-toggle-button-checked-ink-color: 'var(--accent-color)'
      paper-toggle-button-unchecked-button-color: 'var(--disabled-text-color)'
      paper-toggle-button-unchecked-bar-color: 'var(--disabled-text-color)'
      paper-toggle-button-unchecked-ink-color: 'var(--disabled-text-color)'

      # Sliders
      paper-slider-knob-color: 'var(--accent-color)'
      paper-slider-knob-start-color: 'var(--accent-color)'
      paper-slider-pin-color: 'var(--accent-color)'

# Home Assistant Customer UI: https://github.com/andrey-git/home-assistant-custom-ui
customizer:
  custom_ui: hosted

# Lovelace Theme For Time Of Day
automation:
  - alias: Home Assistant Frontend - Set Theme at Startup
    initial_state: 'on'
    trigger:
    - platform: homeassistant
      event: start
    action:
      service: frontend.set_theme
      data_template:
        name: > 
          {% if is_state('sun.sun', 'above_horizon') %}
            default
          {% else %}
            midnight
          {% endif %}
          
  - alias: Home Assistant Frontend - Set dark theme at night
    initial_state: true
    trigger:
      - platform: state
        entity_id: sun.sun
        to: 'below_horizon'
    action:
      - service: frontend.set_theme
        data:
          name: midnight
            
  - alias: Home Assistant Frontend - Set light theme at day
    initial_state: true
    trigger:
      - platform: state
        entity_id: sun.sun
        to: 'above_horizon'
    action:
      - service: frontend.set_theme
        data:
          name: default

# Additional Panels
panel_iframe:
  home_server_dashboard:
    title: Home Server Dashboard
    url: 'http://192.168.1.111/'
    icon: mdi:monitor-dashboard
    require_admin: true
  recipe_manager:
    title: Recipe Manager
    url: 'http://192.168.1.111:4000/beta/'
    icon: mdi:food-variant
    require_admin: false
