binary_sensor:
  - platform: template
    sensors:
      garage_external_door:
        friendly_name: Garage External Door
        device_class: door
        value_template: "{{ is_state('binary_sensor.swann_door_1', 'on') }}"
        availability_template: "{{ not is_state('binary_sensor.swann_door_1', 'unavailable') }}"