script:
  #Trigger the Hue lights scene for movie watching
  set_movie_lighting:
    sequence:
    - service: hue.hue_activate_scene
      data: 
        group_name: "Theatre Room"
        scene_name: "Movie Watching"
    - service: light.turn_off
      data:
        entity_id: light.entry_hall_lights
    - service: light.turn_off
      data: 
        entity_id: light.theatre_room_ceiling
    alias: Movie Lighting Scene
    

  #Get the theatre room ready  
  time_for_a_movie:
    alias: Time For A Movie
    sequence:
      - service: light.turn_off #this would be triggered anyway, but this call makes it occur faster
        entity_id: light.axis_gear_034e1400_1 
      - service: script.turn_on #set the lighting
        entity_id:
          - script.set_movie_lighting 
      - service: media_player.turn_on #turn on the TV
        entity_id:
          - media_player.theatre_room_tv 
      - delay: #wait for the tv to switch on
          seconds: 10
      - service: media_player.select_source #switch TV to netflix
        data:
          entity_id: media_player.theatre_room_tv
          source: "Netflix"

  #Finished with the theatre room  
  done_with_the_theatre_room:
    alias: Done With The Theatre Room
    sequence:
      - service: media_player.turn_off #turn on the TV
        entity_id:
          - media_player.theatre_room_tv 
      - service: light.turn_off
        entity_id:
          - light.theatre_room_left_lamp
          - light.theatre_room_right_lamp
          - light.theatre_room_ceiling

  #Slowly fade in the lights after the movie has finished
  movie_has_finished:
    alias: Movie Has Finished
    sequence:
      - service: light.turn_on
        entity_id:
          - light.theatre_room_left_lamp
          - light.theatre_room_right_lamp
        data:
          rgb_color: [255,255,255]
          brightness_pct: 100
          transition: 60
      - delay: #wait for the lamps to finish
          seconds: 60
      - service: light.turn_on
        entity_id:
          - light.theatre_room_ceiling
        data:
          brightness_pct: 1



automation:
  - alias: Theatre Room Blinds - Close
    trigger:
      - platform: sun
        event: sunset
      - platform: state
        entity_id: alarm_control_panel.alarm_com
        to: 'armed'
      - platform: state
        entity_id: media_player.theatre_room_tv
        from: 'off' #from off = turning on
    action:
      - service: light.turn_off
        entity_id: light.axis_gear_034e1400_1
        
  - alias: Theatre Room Blinds - Open
    trigger:
      - platform: sun
        event: sunrise
      - platform: state
        entity_id: alarm_control_panel.alarm_com
        to: 'disarmed'
      - platform: state
        entity_id: media_player.theatre_room_tv
        to: 'off'
    condition:
      condition: and #ONLY open if house is disarmed AND TV is off AND it's day time
      conditions:
        - condition: state 
          entity_id: sun.sun
          state: 'above_horizon' #day time
        - condition: state
          entity_id: alarm_control_panel.alarm_com
          state: 'disarmed'
        - condition: state
          entity_id: media_player.theatre_room_tv
          state: 'off'
    action:
      - service: light.turn_on
        entity_id: light.axis_gear_034e1400_1
        data:
          brightness: 254 #maximum
        
            

############## LG TV ##############

# Turn on wake-on-lan support
wake_on_lan:

# LG TV
media_player:
  - platform: webostv
    host: 192.168.1.150
    name: Theatre Room TV
    filename: webostv.conf
    timeout: 5
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: "A8:23:FE:E4:84:05"
    customize:
      sources:
        - livetv
        - youtube
        - makotv
        - netflix

############## LG TV ##############

# The theatre room blinds have to be manually set up as a light, as 
# by default they are a switch which cannot control the blind height
zha:
  device_config:
    00:24:46:00:00:14:4e:03-1:
      type: 'light' #FIXME when ZHA covers are supported
