############## LEAVING THE HOUSE ##############

- alias: Notify If Alarm Not Set When Nobody Is Home
  trigger:
    - platform: zone
      entity_id: device_tracker.lauras_iphone
      zone: zone.home
      event: leave
    - platform: zone
      entity_id: device_tracker.michael_michaelgalaxys10_2
      zone: zone.home
      event: leave
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ not is_state('device_tracker.lauras_iphone','home') }}"
      - condition: template
        value_template: "{{ not is_state('device_tracker.michael_michaelgalaxys10_2','home') }}"
      - condition: state
        entity_id: alarm_control_panel.alarm_com
        state: 'disarmed'
  action:
    - service: notify.pushbullet #notify Michael
      data:
        message: The house alarm was not set.
    - service: notify.notify # notify Laura
      data:
        message: The house alarm was not set.
        
- alias: Turn Off House When Alarm Is Set
  trigger:
    platform: state
    entity_id: alarm_control_panel.alarm_com
    from: 'disarmed'
    to: 'armed_away'
  action:
    - service: light.turn_off #lights
      entity_id: 
        - group.all_lights
    - service: script.aircon_turn_off #aircon
    - service: media_player.turn_off #tv & speakers
      entity_id:
        - media_player.theatre_room_tv 
        - media_player.all_rooms
        
############## LEAVING THE HOUSE ##############

############## LOVELACE THEME FOR TIME OF DAY ##############

- alias: 'Set theme at startup'
  initial_state: 'on'
  trigger:
   - platform: homeassistant
     event: start
  action:
    service: frontend.set_theme
    data_template:
      name: > 
        {% if is_state('sun.sun', 'above_horizon') %}
          default
        {% else %}
          midnight
        {% endif %}
        
- alias: 'Set dark theme at night'
  initial_state: true
  trigger:
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
  action:
    - service: frontend.set_theme
      data:
        name: midnight
          
- alias: 'Set light theme at day'
  initial_state: true
  trigger:
    - platform: state
      entity_id: sun.sun
      to: 'above_horizon'
  action:
    - service: frontend.set_theme
      data:
        name: default

############## LOVELACE THEME FOR TIME OF DAY ##############
