
############## DOORS LEFT OPEN ##############

#if garage door left open, send a push notification.
- alias: Notify If Garage Door Left Open For 5 Minutes
  trigger:
    platform: time_pattern
    minutes: '/1' #run every minute
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: cover.aeon_labs_zw062_garage_door_controller_barrier_state_label
        state: 'open'
        for:
          minutes: 5
  action:
    - service: notify.pushbullet
      data:
        message: Garage door was left open.
        
#if garage door unreachable, send a push notification.
- alias: Notify If Garage Door Is Unreachable
  trigger:
    platform: time_pattern
    minutes: '/1' #run every minute
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: cover.aeon_labs_zw062_garage_door_controller_barrier_state_label
        state: 'unknown'
        for:
          minutes: 5
  action:
    - service: notify.pushbullet
      data:
        message: Garage door cannot be reached.
        
#if not closing garage when leaving home, send a notification. 
- alias: Notify If Garage Door Left Open When Leaving Home
  trigger:
    platform: zone
    entity_id: device_tracker.michael_michaelgalaxys10_2
    zone: zone.home
    event: leave
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: cover.aeon_labs_zw062_garage_door_controller_barrier_state_label
        state: 'open'
  action:
    - service: notify.pushbullet
      data:
        message: Garage door was left open.

############## DOORS LEFT OPEN ##############

############## SWITCH ON HALLWAY LIGHTS ##############

- alias: Turn On Hallway Light If Garage Opened After Sunset
  trigger:
    platform: state
    entity_id: cover.aeon_labs_zw062_garage_door_controller_barrier_state_label
  condition:
    condition: and
    conditions:
      - condition: state  # from sunset until sunrise
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: or
        conditions:
          - condition: state
            entity_id: cover.aeon_labs_zw062_garage_door_controller_barrier_state_label
            state: 'open'
          - condition: state
            entity_id: cover.aeon_labs_zw062_garage_door_controller_barrier_state_label
            state: 'opening'
  action:
    - service: light.turn_on
      entity_id:
        - light.entry_hall_lights

- alias: Turn On Hallway Light If Front Door Opened After Sunset
  trigger:
    platform: state
    entity_id: sensor.front_door
  condition:
    condition: and
    conditions:
      - condition: state  # from sunset until sunrise
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: sensor.front_door
        state: 'Open'
  action:
    - service: light.turn_on
      entity_id:
        - light.entry_hall_lights
        
    
############## SWITCH ON HALLWAY LIGHTS ##############

############## LAURA LEAVING WORK ##############

- alias: Notify Michael If Laura Leaving Work
  trigger:
    platform: zone
    entity_id: device_tracker.lauras_iphone
    zone: zone.laura_s_work
    event: leave
  action:
    - service: notify.pushbullet
      data:
        message: Laura is leaving work.

############## LAURA LEAVING WORK ##############

############## LEAVING THE HOUSE ##############

- alias: Notify If Alarm Not Set When Nobody Is Home
  trigger:
    - platform: zone
      entity_id: device_tracker.lauras_iphone
      zone: zone.home
      event: leave
    - platform: zone
      entity_id: device_tracker.michael_michaelgalaxys10_2
      zone: zone.home
      event: leave
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ not is_state('device_tracker.lauras_iphone','home') }}"
      - condition: template
        value_template: "{{ not is_state('device_tracker.michael_michaelgalaxys10_2','home') }}"
      - condition: state
        entity_id: alarm_control_panel.alarm_com
        state: 'disarmed'
  action:
    - service: notify.pushbullet #notify Michael
      data:
        message: The house alarm was not set.
    - service: notify.notify # notify Laura
      data:
        message: The house alarm was not set.
        
- alias: Turn Off House When Alarm Is Set
  trigger:
    platform: state
    entity_id: alarm_control_panel.alarm_com
    from: 'disarmed'
    to: 'armed_away'
  action:
    - service: light.turn_off #lights
      entity_id: 
        - group.all_lights
    - service: script.aircon_turn_off #aircon
    - service: media_player.turn_off #tv & speakers
      entity_id:
        - media_player.theatre_room_tv 
        - media_player.all_rooms
        
############## LEAVING THE HOUSE ##############

############## LOVELACE THEME FOR TIME OF DAY ##############

- alias: 'Set theme at startup'
  initial_state: 'on'
  trigger:
   - platform: homeassistant
     event: start
  action:
    service: frontend.set_theme
    data_template:
      name: > 
        {% if is_state('sun.sun', 'above_horizon') %}
          default
        {% else %}
          midnight
        {% endif %}
        
- alias: 'Set dark theme at night'
  initial_state: true
  trigger:
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
  action:
    - service: frontend.set_theme
      data:
        name: midnight
          
- alias: 'Set light theme at day'
  initial_state: true
  trigger:
    - platform: state
      entity_id: sun.sun
      to: 'above_horizon'
  action:
    - service: frontend.set_theme
      data:
        name: default

############## LOVELACE THEME FOR TIME OF DAY ##############
