############## AIRCON ##############

- alias: Aircon - Adjust Temperature From Slider
  trigger: 
    platform: state
    entity_id: input_number.aircon_temperature
  action:
    - service: rest_command.aircon_control
      data_template:
        command: '{"ac1":{"info":{"setTemp":{{ states.input_number.aircon_temperature.state | int }}}}}'
          
- alias: Aircon - Adjust Temperature From Sensor
  trigger: 
    platform: state
    entity_id: sensor.aircon_temperature
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.aircon_temperature
        value: "{{ states.sensor.aircon_temperature.state }}"
        
- alias: Aircon - Adjust Countdown Timer From Slider
  trigger: 
    platform: state
    entity_id: input_number.aircon_countdown_timer
  action:
    - service: rest_command.aircon_control
      data_template:
        command: '{"ac1":{"info":{"countDownToOff":{{ states.input_number.aircon_countdown_timer.state | int }}}}}'
          
- alias: Aircon - Adjust Countdown Timer From Sensor
  trigger: 
    platform: state
    entity_id: sensor.aircon_countdown_timer
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.aircon_countdown_timer
        value: "{{ states.sensor.aircon_countdown_timer.state }}"

- alias: Aircon - Set Run Mode From Selector
  trigger: 
    platform: state
    entity_id: input_select.aircon_run_mode
  action:
    - service: rest_command.aircon_control
      data_template:
        command: '{"ac1":{"info":{"mode":{{ states.input_select.aircon_run_mode.state }}}}}'

- alias: Aircon - Set Run Mode From Sensor
  trigger: 
    platform: state
    entity_id: sensor.aircon_run_mode
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.aircon_run_mode
        option: "{{ states.sensor.aircon_run_mode.state }}"

############## AIRCON ##############


- alias: Morning Warmth
  trigger:
    - platform: time
      at: '06:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: numeric_state
      entity_id: weather.bom_perth
      below: '6'
      value_template: '{{ state.attributes.temperature }}'
  action:
    - service: script.aircon_warm_master
