############## AIRCON ##############

- alias: Aircon - Adjust Temperature From Slider
  trigger: 
    platform: state
    entity_id: input_number.aircon_temperature
  action:
    - service: rest_command.aircon_control
      data_template:
        command: '{"ac1":{"info":{"setTemp":{{ states.input_number.aircon_temperature.state | int }}}}}'
          
- alias: Aircon - Adjust Temperature From Sensor
  trigger: 
    platform: state
    entity_id: sensor.aircon_temperature
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.aircon_temperature
        value: "{{ states.sensor.aircon_temperature.state }}"
        
- alias: Aircon - Adjust Countdown Timer From Slider
  trigger: 
    platform: state
    entity_id: input_number.aircon_countdown_timer
  action:
    - service: rest_command.aircon_control
      data_template:
        command: '{"ac1":{"info":{"countDownToOff":{{ states.input_number.aircon_countdown_timer.state | int }}}}}'
          
- alias: Aircon - Adjust Countdown Timer From Sensor
  trigger: 
    platform: state
    entity_id: sensor.aircon_countdown_timer
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.aircon_countdown_timer
        value: "{{ states.sensor.aircon_countdown_timer.state }}"

- alias: Aircon - Set Run Mode From Selector
  trigger: 
    platform: state
    entity_id: input_select.aircon_run_mode
  action:
    - service: rest_command.aircon_control
      data_template:
        command: '{"ac1":{"info":{"mode":{{ states.input_select.aircon_run_mode.state }}}}}'

- alias: Aircon - Set Run Mode From Sensor
  trigger: 
    platform: state
    entity_id: sensor.aircon_run_mode
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.aircon_run_mode
        option: "{{ states.sensor.aircon_run_mode.state }}"

- alias: Morning Warmth
  trigger:
    - platform: time
      at: '06:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: numeric_state
      entity_id: weather.bom_perth
      below: '8'
      value_template: '{{ state.attributes.temperature }}'
  action:
    - service: script.aircon_warm_master

############## AIRCON ##############

############## DOORS LEFT OPEN ##############

#if garage door left open, send a push notification.
- alias: Notify If Garage Door Left Open For 5 Minutes
  trigger:
    platform: time_pattern
    minutes: '/1' #run every minute
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: cover.aeon_labs_zw062_garage_door_controller_barrier_state_label
        state: 'open'
        for:
          minutes: 5
  action:
    - service: notify.pushbullet
      data:
        message: Garage door was left open.
        
#if garage door unreachable, send a push notification.
- alias: Notify If Garage Door Is Unreachable
  trigger:
    platform: time_pattern
    minutes: '/1' #run every minute
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: cover.aeon_labs_zw062_garage_door_controller_barrier_state_label
        state: 'unknown'
        for:
          minutes: 5
  action:
    - service: notify.pushbullet
      data:
        message: Garage door cannot be reached.
        
#if not closing garage when leaving home, send a notification. 
- alias: Notify If Garage Door Left Open When Leaving Home
  trigger:
    platform: zone
    entity_id: device_tracker.michael_michaelgalaxys10
    zone: zone.home
    event: leave
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: cover.aeon_labs_zw062_garage_door_controller_barrier_state_label
        state: 'open'
  action:
    - service: notify.pushbullet
      data:
        message: Garage door was left open.

############## DOORS LEFT OPEN ##############

############## SWITCH ON HALLWAY LIGHTS ##############

- alias: Turn On Hallway Light If Garage Opened After Sunset
  trigger:
    platform: state
    entity_id: cover.aeon_labs_zw062_garage_door_controller_barrier_state_label
  condition:
    condition: and
    conditions:
      - condition: state  # from sunset until sunrise
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: or
        conditions:
          - condition: state
            entity_id: cover.aeon_labs_zw062_garage_door_controller_barrier_state_label
            state: 'open'
          - condition: state
            entity_id: cover.aeon_labs_zw062_garage_door_controller_barrier_state_label
            state: 'opening'
  action:
    - service: light.turn_on
      entity_id:
        - light.fibaro_system_fgd212_dimmer_2_level_2 #hallway light

- alias: Turn On Hallway Light If Front Door Opened After Sunset
  trigger:
    platform: state
    entity_id: sensor.front_door
  condition:
    condition: and
    conditions:
      - condition: state  # from sunset until sunrise
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: sensor.front_door
        state: 'Open'
  action:
    - service: light.turn_on
      entity_id:
        - light.fibaro_system_fgd212_dimmer_2_level_2 #hallway light        
        
    
############## SWITCH ON HALLWAY LIGHTS ##############

