homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Australia/Perth
  # Customization file
  customize: !include customize.yaml
  # Package config: https://www.home-assistant.io/docs/configuration/packages/#create-a-packages-folder
  packages: !include_dir_named packages 

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include themes.yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Discover some devices automatically
discovery:
ssdp:
zeroconf:

# Home Assistant Customer UI: https://github.com/andrey-git/home-assistant-custom-ui
customizer:
  custom_ui: hosted

# Todoist To-Do and Shopping Lists
calendar:
  - platform: todoist
    token: !secret todoist_api_key

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
script: !include scripts.yaml

# Automation scripts
automation: !include automations.yaml

# Sensors
sensor: !include sensors.yaml
binary_sensor:
  # Ring doorbell events (ie. ring/motion)
  - platform: ring

# Aeotec Z-Wave Stick
zwave:
  usb_path: /dev/ttyACM0
  device_config: !include zwave_device_config.yaml
  
# Push Notifications  
notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key
    
############## AIRCON ##############

# AIR CON COMMAND
rest_command:
  aircon_control:
    url: 'http://192.168.1.106:2025/setAircon?json={{ command }}'
    method: 'GET'


# AIR CON SWITCHES
switch: !include switches.yaml

# AIR CON TEMPERATURE DIAL
input_number:
  aircon_temperature:
    name: Aircon Temperature
    initial: 23
    min: 16
    max: 32
    step: 1
  aircon_countdown_timer:
    name: Aircon Countdown Timer
    initial: 0
    min: 0
    max: 300
    step: 15
    
 # AIR CON RUN MODE
input_select:
    aircon_run_mode:
        name: Aircon Run Mode
        options:
          - cool
          - heat
          - vent
          - dry
        initial: cool  
        icon: mdi:air-conditioner
    

############## AIRCON ##############


############## LG TV ##############

# Turn on wake-on-lan support
wake_on_lan:

# LG TV
media_player:
  - platform: webostv
    host: 192.168.1.150
    name: Theatre Room TV
    filename: webostv.conf
    timeout: 5
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: "A8:23:FE:E4:84:05"
    customize:
      sources:
        - livetv
        - youtube
        - makotv
        - netflix


############## LG TV ##############


############## DOORBELL ##############

# RING DOORBELL
ring:
  username: !secret ring_username
  password: !secret ring_password
  
# camera is currently not in use due to raspberry pi hardware limitations
#camera:
#  - platform: ring
#    scan_interval: 90

############## DOORBELL ##############


############## ALARM.COM ##############

alarm_control_panel:
  platform: alarmdotcom
  scan_interval: 10
  username: !secret alarmdotcom_username
  password: !secret alarmdotcom_password

############## ALARM.COM ##############


############## WEATHER ##############

weather:
  - platform: bom
    station: IDW60901.94608
sun:

############## WEATHER ##############

############## PEOPLE ##############

ios:

############## PEOPLE ##############

############## GOOGLE ASSISTANT ##############

cloud:
  google_actions:
    filter:
      exclude_domains:
        - media_player
        - automation
        - script
        - switch
        - group
        - cover
        - input_number
        - sensor
      include_entities:
        - script.set_movie_lighting
        - script.aircon_warm_master
        - script.aircon_fan_master
        - script.aircon_cool_central_living
        - script.time_for_a_movie
        - script.done_with_the_theatre_room
        - switch.aircon_on_off
        - switch.aircon_zone_bed23
        - switch.aircon_zone_living
        - switch.aircon_zone_master
        - switch.aircon_zone_theatre
        - group.aircon_vents
      exclude_entities:
        - light.theatre_room
        - light.theatre_room_2
        - light.fibaro_system_fgd212_dimmer_2_level
        - light.fibaro_system_fgd212_dimmer_2_level_3
        - light.office
        - light.office_2
    entity_config:
      switch.aircon_on_off:
        name: Aircon
        aliases:
          - Aircon
          - Airconditioner
      switch.aircon_zone_bed23:
        name: Front Room Vents
        aliases:
          - Front Room Vents
          - Study Vent
          - Office Vent
          - Sewing Room Vent
      switch.aircon_zone_living:
        name: Center House Vents
        aliases:
          - Center House Vents
          - Living Room Vent
          - Dining Room Vent
          - Central Living Vents
      switch.aircon_zone_master:
        name: Master Bedroom Vent
        aliases:
          - Master Bedroom Vent
          - Bedroom Vent
      switch.aircon_zone_theatre:
        name: Theatre Room Vent
        aliases:
          - Theatre Room Vent
          - Theatre Vent
    

############## GOOGLE ASSISTANT ##############

############## ADDITIONAL PANELS ##############

panel_iframe:
  router:
    title: 'D-Link Router'
    url: 'http://192.168.1.1'
    icon: mdi:router-wireless
    require_admin: true
  sqlite_web:
    title: SQLite Web
    icon: mdi:database
    url: http://192.168.1.52:6210
    require_admin: true

############## ADDITIONAL PANELS ##############

############## ZONES ##############

zone:
  - name: Laura's Work
    latitude: !secret zone_laura_work_latitude
    longitude: !secret zone_laura_work_longitude
    radius: 600
    icon: mdi:briefcase

  - name: Michael's Work
    latitude: !secret zone_michael_work_latitude
    longitude: !secret zone_michael_work_longitude
    radius: 120
    icon: mdi:briefcase

  # This will override the default home zone
  - name: Home
    latitude: !secret zone_home_latitude
    longitude: !secret zone_home_longitude
    radius: 200
    icon: mdi:home

############## ZONES ##############
