homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Customization file
  customize: !include customize.yaml
  # Package config: https://www.home-assistant.io/docs/configuration/packages/#create-a-packages-folder
  packages: !include_dir_named packages 

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include themes.yaml

automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml


# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Discover some devices automatically
discovery:
ssdp:
zeroconf:

# Home Assistant Customer UI: https://github.com/andrey-git/home-assistant-custom-ui
customizer:
  custom_ui: hosted

# Todoist To-Do and Shopping Lists
calendar:
  - platform: todoist
    token: !secret todoist_api_key
    
# Elastic search output
elastic:
  url: http://192.168.1.111:9200
  exclude:
    entities: ['sensor.es_cluster_health', 'sensor.es_publish_queue', 'sun.sun']

# Text to speech
tts:
  - platform: google_translate

binary_sensor:
  # Ring doorbell events (ie. ring/motion)
  - platform: ring

# Aeotec Z-Wave Stick
zwave:
  usb_path: /zwaveusbstick
  device_config: !include zwave_device_config.yaml


############## ALARM.COM ##############

alarm_control_panel:
  platform: alarmdotcom
  scan_interval: 10
  username: !secret alarmdotcom_username
  password: !secret alarmdotcom_password

############## ALARM.COM ##############

############## WEATHER ##############

weather:
  - platform: bom
    station: IDW60901.94608
sun:

############## WEATHER ##############

############## BREAKING CHANGES ##############

breaking_changes:
  scan_interval: 600 #10 minutes

############## BREAKING CHANGES ##############

############## ADDITIONAL PANELS ##############

panel_iframe:
  router_primary:
    title: 'Router (Primary)'
    url: 'http://192.168.1.1'
    icon: mdi:router-wireless
    require_admin: true
  router_secondary:
    title: 'Router (Secondary)'
    url: 'http://192.168.1.2'
    icon: mdi:router-wireless
    require_admin: true
  portainer:
    title: Portainer
    url: 'http://192.168.1.111:9000'
    icon: mdi:docker
    require_admin: true
  elk:
    title: ELK
    url: 'http://192.168.1.111:5601'
    icon: mdi:database
    require_admin: true
  elk_money_balance:
    title: Money Balance
    url: 'http://192.168.1.111:5601/app/kibana#/dashboard/d8425c20-5a84-11e7-9da3-818b9c9525ff?_g=(refreshInterval%3A(pause%3A!t%2Cvalue%3A0)%2Ctime%3A(from%3Anow-1y%2Cto%3Anow))'
    icon: mdi:currency-usd
    require_admin: true
  elk_money_spent:
    title: Money Spent
    url: 'http://192.168.1.111:5601/app/kibana#/dashboard/0f7fa450-ead0-11e7-bf13-553f043d4230?_g=(refreshInterval%3A(pause%3A!t%2Cvalue%3A0)%2Ctime%3A(from%3Anow-1y%2Cto%3Anow))'
    icon: mdi:currency-usd-off
    require_admin: true
    
############## ADDITIONAL PANELS ##############


