homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Australia/Perth
  # Customization file
  customize: !include customize.yaml
  # Package config: https://www.home-assistant.io/docs/configuration/packages/#create-a-packages-folder
  packages: !include_dir_named packages 

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include themes.yaml

automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml


# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Discover some devices automatically
discovery:
ssdp:
zeroconf:

# Home Assistant Customer UI: https://github.com/andrey-git/home-assistant-custom-ui
customizer:
  custom_ui: hosted

# Todoist To-Do and Shopping Lists
calendar:
  - platform: todoist
    token: !secret todoist_api_key
    
# Elastic search output
elastic:
  url: http://192.168.1.111:9200
  exclude:
    entities: ['sensor.es_cluster_health', 'sensor.es_publish_queue', 'sun.sun']

# Text to speech
tts:
  - platform: google_translate

binary_sensor:
  # Ring doorbell events (ie. ring/motion)
  - platform: ring

# Aeotec Z-Wave Stick
zwave:
  usb_path: /zwaveusbstick
  device_config: !include zwave_device_config.yaml
  
# Push Notifications  
notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key
    


############## LG TV ##############

# Turn on wake-on-lan support
wake_on_lan:

# LG TV
media_player:
  - platform: webostv
    host: 192.168.1.150
    name: Theatre Room TV
    filename: webostv.conf
    timeout: 5
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: "A8:23:FE:E4:84:05"
    customize:
      sources:
        - livetv
        - youtube
        - makotv
        - netflix


############## LG TV ##############


############## DOORBELL ##############

# RING DOORBELL
ring:
  username: !secret ring_username
  password: !secret ring_password

############## DOORBELL ##############


############## ALARM.COM ##############

alarm_control_panel:
  platform: alarmdotcom
  scan_interval: 10
  username: !secret alarmdotcom_username
  password: !secret alarmdotcom_password

############## ALARM.COM ##############


############## WEATHER ##############

weather:
  - platform: bom
    station: IDW60901.94608
sun:

############## WEATHER ##############

############## PEOPLE ##############

ios:

############## PEOPLE ##############

############## BREAKING CHANGES ##############

breaking_changes:
  scan_interval: 600 #10 minutes

############## BREAKING CHANGES ##############

############## GOOGLE ASSISTANT ##############

cloud:
  google_actions:
    filter:
      exclude_domains:
        - media_player
        - automation
        - script
        - switch
        - group
        - cover
        - input_number
        - sensor
      include_entities:
        - script.set_movie_lighting
        - script.aircon_warm_master
        - script.aircon_fan_master
        - script.aircon_cool_central_living
        - script.time_for_a_movie
        - script.done_with_the_theatre_room
        - script.roomba_clean
        - switch.aircon_on_off
        - switch.aircon_zone_bed23
        - switch.aircon_zone_living
        - switch.aircon_zone_master
        - switch.aircon_zone_theatre
        - group.aircon_vents
      exclude_entities:
        - light.theatre_room
        - light.theatre_room_2
        - light.fibaro_system_fgd212_dimmer_2_level_2
        - light.fibaro_system_fgd212_dimmer_2_level_4
        - light.office
        - light.office_2
    entity_config:
      switch.aircon_on_off:
        name: Aircon
        aliases:
          - Aircon
          - Airconditioner
      switch.aircon_zone_bed23:
        name: Front Room Vents
        aliases:
          - Front Room Vents
          - Study Vent
          - Office Vent
          - Sewing Room Vent
      switch.aircon_zone_living:
        name: Center House Vents
        aliases:
          - Center House Vents
          - Living Room Vent
          - Dining Room Vent
          - Central Living Vents
      switch.aircon_zone_master:
        name: Master Bedroom Vent
        aliases:
          - Master Bedroom Vent
          - Bedroom Vent
      switch.aircon_zone_theatre:
        name: Theatre Room Vent
        aliases:
          - Theatre Room Vent
          - Theatre Vent

############## GOOGLE ASSISTANT ##############

############## ADDITIONAL PANELS ##############

panel_iframe:
  router_primary:
    title: 'Router (Primary)'
    url: 'http://192.168.1.1'
    icon: mdi:router-wireless
    require_admin: true
  router_secondary:
    title: 'Router (Secondary)'
    url: 'http://192.168.1.2'
    icon: mdi:router-wireless
    require_admin: true
  portainer:
    title: Portainer
    url: 'http://192.168.1.111:9000'
    icon: mdi:docker
    require_admin: true
  elk:
    title: ELK
    url: 'http://192.168.1.111:5601'
    icon: mdi:database
    require_admin: true
  elk_money_balance:
    title: Money Balance
    url: 'http://192.168.1.111:5601/app/kibana#/dashboard/d8425c20-5a84-11e7-9da3-818b9c9525ff?_g=(refreshInterval%3A(pause%3A!t%2Cvalue%3A0)%2Ctime%3A(from%3Anow-1y%2Cto%3Anow))'
    icon: mdi:currency-usd
    require_admin: true
  elk_money_spent:
    title: Money Spent
    url: 'http://192.168.1.111:5601/app/kibana#/dashboard/0f7fa450-ead0-11e7-bf13-553f043d4230?_g=(refreshInterval%3A(pause%3A!t%2Cvalue%3A0)%2Ctime%3A(from%3Anow-1y%2Cto%3Anow))'
    icon: mdi:currency-usd-off
    require_admin: true
    
############## ADDITIONAL PANELS ##############

############## ZONES ##############

zone:
  - name: Laura's Work
    latitude: !secret zone_laura_work_latitude
    longitude: !secret zone_laura_work_longitude
    radius: 600
    icon: mdi:briefcase

  - name: Michael's Work
    latitude: !secret zone_michael_work_latitude
    longitude: !secret zone_michael_work_longitude
    radius: 120
    icon: mdi:briefcase

  # This will override the default home zone
  - name: Home
    latitude: !secret zone_home_latitude
    longitude: !secret zone_home_longitude
    radius: 220
    icon: mdi:home

############## ZONES ##############
