homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: -33.3371
  longitude: 115.6743
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Australia/Perth
  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Turn on wake-on-lan support
wake_on_lan:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Discover some devices automatically
discovery:



# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml



# Sensors
sensor:
  # Weather prediction
  - platform: yr
  
  # AIR CON SENSORS
  - platform: rest
    resource: http://192.168.1.106:2025/getSystemData
    name: aircon_sensor
    value_template: '{{ value_json.aircons.ac1.info.state }}'
    scan_interval: 5
    json_attributes:
      - aircons
  - platform: template
    sensors:
      aircon_zone_living: #zone z01
        value_template: '{{ states.sensor.aircon_sensor.attributes["aircons"]["ac1"]["zones"]["z01"]["state"] }}'
      aircon_zone_theatre: #zone z02
        value_template: '{{ states.sensor.aircon_sensor.attributes["aircons"]["ac1"]["zones"]["z02"]["state"] }}'
      aircon_zone_master: #zone z03
        value_template: '{{ states.sensor.aircon_sensor.attributes["aircons"]["ac1"]["zones"]["z03"]["state"] }}'
      aircon_zone_bed23: #zone z04
        value_template: '{{ states.sensor.aircon_sensor.attributes["aircons"]["ac1"]["zones"]["z04"]["state"] }}'

##################################

# AIR CON COMMAND
rest_command:
  aircon_control:
    url: 'http://192.168.1.106:2025/setAircon?json={{ command }}'
    method: 'GET'

# AIR CON SWITCHES
switch:
  - platform: template
    switches:
    
      aircon_on_off: #overall aircon control
        value_template: "{{ is_state('sensor.aircon_sensor', 'on') }}"
        turn_on:
          service: rest_command.aircon_control
          data:
            command: '{"ac1":{"info":{"state":"on"}}}'
        turn_off:
          service: rest_command.aircon_control
          data:
            command: '{"ac1":{"info":{"state":"off"}}}'
            
      aircon_zone_living: #zone z01
        value_template: "{{ is_state('sensor.aircon_zone_living', 'open') }}"
        turn_on:
          service: rest_command.aircon_control
          data:
            command: '{"ac1":{"zones":{"z01":{"state":"open"}}}}'
        turn_off:
          service: rest_command.aircon_control
          data:
            command: '{"ac1":{"zones":{"z01":{"state":"close"}}}}'
            
      aircon_zone_theatre: #zone z02
        value_template: "{{ is_state('sensor.aircon_zone_theatre', 'open') }}"
        turn_on:
          service: rest_command.aircon_control
          data:
            command: '{"ac1":{"zones":{"z02":{"state":"open"}}}}'
        turn_off:
          service: rest_command.aircon_control
          data:
            command: '{"ac1":{"zones":{"z02":{"state":"close"}}}}'      
            
      aircon_zone_master: #zone z03
        value_template: "{{ is_state('sensor.aircon_zone_master', 'open') }}"
        turn_on:
          service: rest_command.aircon_control
          data:
            command: '{"ac1":{"zones":{"z03":{"state":"open"}}}}'
        turn_off:
          service: rest_command.aircon_control
          data:
            command: '{"ac1":{"zones":{"z03":{"state":"close"}}}}'  
       
      aircon_zone_bed23: #zone z04
        value_template: "{{ is_state('sensor.aircon_zone_bed23', 'open') }}"
        turn_on:
          service: rest_command.aircon_control
          data:
            command: '{"ac1":{"zones":{"z04":{"state":"open"}}}}'
        turn_off:
          service: rest_command.aircon_control
          data:
            command: '{"ac1":{"zones":{"z04":{"state":"close"}}}}'

##################################

# LG TV
media_player:
  - platform: webostv
    host: 192.168.1.150
    name: Theatre Room TV
    filename: webostv.conf
    timeout: 5
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: "A8:23:FE:E4:84:05"
    customize:
      sources:
        - livetv
        - youtube
        - makotv
        - netflix
