resources:
  - type: module
    url: /local/custom-lovelace/weather-card/weather-card.js
  - type: module
    url: /local/mini-media-player-bundle.js?v=1.1.3
title: Treeby Home
views:
  - badges:
      - person.michael
      - person.laura
      - sensor.yr_symbol
      - sun.sun
    cards:
      - entities:
          - entity: light.theatre_room_left_lamp
          - entity: light.theatre_room_right_lamp
        show_header_toggle: true
        title: Lights
        type: entities
      - entities:
          - entity: sensor.ring_front_door_last_motion
          - entity: sensor.ring_front_door_last_ding
          - entity: sensor.ring_downstairs_wifi_signal_category
        show_header_toggle: false
        title: Ring Doorbell
        type: entities
      - cards:
          - entity: weather.bom_perth
            icons: /local/custom-lovelace/weather-card/icons/
            name: Treeby
            type: 'custom:weather-card'
          - entities:
              - entity: sensor.bom_forecast_perth_weather_1
              - entity: sensor.bom_forecast_perth_weather_2
              - entity: sensor.bom_forecast_perth_weather_3
              - entity: sensor.bom_forecast_perth_weather_4
              - entity: sensor.bom_forecast_perth_weather_5
              - entity: sensor.bom_forecast_perth_weather_6
            show_header_toggle: false
            title: Weather Forecast
            type: entities
        type: vertical-stack
      - cards:
          - entities:
              - entity: switch.aircon_on_off
                name: Aircon On/Off
              - entity: input_select.aircon_run_mode
              - entity: sensor.aircon_temperature
                name: Aircon Temperature
              - entity: input_number.aircon_temperature
                name: Set Temperature
                icon: 'mdi:temperature-celsius'
            show_header_toggle: false
            title: Aircon Control
            type: entities
          - type: conditional
            conditions:
              - entity: switch.aircon_on_off
                state: 'on'
            card:
              type: vertical-stack
              cards:
                - type: entities
                  entities:
                    - entity: input_number.aircon_countdown_timer
                      icon: 'mdi:timer-sand'
                  show_header_toggle: false
                  title: Countdown To Off
                - type: horizontal-stack
                  cards:
                    - type: entity-button
                      tap_action:
                        action: call-service
                        service: input_number.set_value
                        service_data:
                          entity_id: input_number.aircon_countdown_timer
                          value: 30
                      hold_action:
                        action: none
                      show_icon: true
                      show_name: true
                      icon: 'mdi:clock-outline'
                      entity: sensor.aircon_countdown_timer
                      name: 30 Minutes
                    - type: entity-button
                      tap_action:
                        action: call-service
                        service: input_number.set_value
                        service_data:
                          entity_id: input_number.aircon_countdown_timer
                          value: 60
                      hold_action:
                        action: none
                      show_icon: true
                      show_name: true
                      icon: 'mdi:clock-outline'
                      entity: sensor.aircon_countdown_timer
                      name: 1 Hour
                    - type: entity-button
                      tap_action:
                        action: call-service
                        service: input_number.set_value
                        service_data:
                          entity_id: input_number.aircon_countdown_timer
                          value: 90
                      hold_action:
                        action: none
                      show_icon: true
                      show_name: true
                      icon: 'mdi:clock-outline'
                      entity: sensor.aircon_countdown_timer
                      name: 1.5 Hours
                    - type: entity-button
                      tap_action:
                        action: call-service
                        service: input_number.set_value
                        service_data:
                          entity_id: input_number.aircon_countdown_timer
                          value: 120
                      hold_action:
                        action: none
                      show_icon: true
                      show_name: true
                      icon: 'mdi:clock-outline'
                      entity: sensor.aircon_countdown_timer
                      name: 2 Hours
          - entities:
              - entity: switch.aircon_zone_living
                name: Living Area
                icon: 'mdi:air-filter'
              - entity: switch.aircon_zone_theatre
                name: Theatre
                icon: 'mdi:air-filter'
              - entity: switch.aircon_zone_master
                name: Master Bedroom
                icon: 'mdi:air-filter'
              - entity: switch.aircon_zone_bed23
                name: Bedroom 2 & 3
                icon: 'mdi:air-filter'
            show_header_toggle: false
            title: Aircon Zones
            type: entities
          - type: horizontal-stack
            cards:
              - type: entity-button
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.aircon_warm_master
                hold_action:
                  action: none
                show_icon: true
                show_name: true
                entity: script.aircon_warm_master
                name: Cold Morning
                icon: 'mdi:home-automation'
                icon_height: 60px
              - type: entity-button
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.aircon_warm_master
                hold_action:
                  action: none
                show_icon: true
                show_name: true
                entity: script.aircon_warm_master
                name: Cold Night
                icon: 'mdi:home-automation'
                icon_height: 60px
        title: Aircon
        type: vertical-stack
      - entity: alarm_control_panel.alarm_com
        name: House Alarm
        states:
          - arm_home
          - arm_away
        type: alarm-panel
      - entity: sensor.front_door
        type: sensor
        icon: 'mdi:door'
    path: default_view
    title: Home
  - badges: []
    cards:
      - entities:
          - artwork: cover
            entity: media_player.all_rooms
            group: true
            info: scroll
            source: icon
            type: 'custom:mini-media-player'
          - entity: media_player.kitchen_google_home_hub
            group: true
            hide:
              controls: true
            type: 'custom:mini-media-player'
          - entity: media_player.master_bedroom_speaker
            group: true
            hide:
              controls: true
            name: Master Bedroom Google Home
            type: 'custom:mini-media-player'
          - entity: media_player.office_google_home
            group: true
            hide:
              controls: true
            type: 'custom:mini-media-player'
          - entity: media_player.office_pc_speakers
            group: true
            hide:
              controls: true
            type: 'custom:mini-media-player'
          - entity: media_player.theatre_room_google_home
            group: true
            hide:
              controls: true
            type: 'custom:mini-media-player'
        show_header_toggle: false
        title: Music Players
        type: entities
      - entities:
          - artwork: full-cover
            entity: media_player.theatre_room_tv
            hide:
              mute: true
              power_state: false
            info: short
            name: LG TV
            icon: 'mdi:television'
            type: 'custom:mini-media-player'
          - artwork: full-cover
            entity: media_player.theatre_room_chromecast
            hide:
              mute: true
              power_state: false
            info: short
            name: Chromecast
            type: 'custom:mini-media-player'
        show_header_toggle: false
        title: Theatre Room TV
        type: entities
      - entities:
          - artwork: full-cover
            entity: media_player.living_room_chromecast
            hide:
              mute: true
              power_state: false
            info: short
            name: Chromecast
            type: 'custom:mini-media-player'
        show_header_toggle: false
        title: Living Room TV
        type: entities
    title: Media
