resources:
  - type: module
    url: /local/custom-lovelace/weather-card/weather-card.js
  - type: module
    url: /local/mini-media-player-bundle.js?v=1.1.3
title: Treeby Home
views:
  - cards:
      - cards:
          - entity: weather.bom_perth
            icons: /local/custom-lovelace/weather-card/icons/
            name: Treeby
            type: 'custom:weather-card'
          - entities:
              - entity: sensor.bom_forecast_perth_weather_1
              - entity: sensor.bom_forecast_perth_weather_2
              - entity: sensor.bom_forecast_perth_weather_3
              - entity: sensor.bom_forecast_perth_weather_4
              - entity: sensor.bom_forecast_perth_weather_5
              - entity: sensor.bom_forecast_perth_weather_6
            show_header_toggle: false
            title: Weather Forecast
            type: entities
        type: vertical-stack
      - type: glance
        title: Security
        entities:
          - entity: alarm_control_panel.alarm_com
            name: Alarm
          - entity: sensor.front_door
            icon: 'mdi:door'
          - entity: cover.aeon_labs_zw062_garage_door_controller_barrier_state_label
      - type: glance
        entities:
          - entity: light.fibaro_system_fgd212_dimmer_2_level_2
          - entity: light.theatre_room
          - entity: light.theatre_room_left_lamp
          - entity: light.theatre_room_right_lamp
        title: Lights
        columns: 2
        show_icon: true
        show_state: false
      - type: glance
        title: Air Conditioner
        entities:
          - entity: sensor.aircon_sensor
            icon: 'mdi:power'
            name: Air-Con
          - entity: sensor.aircon_run_mode
            icon: 'mdi:air-conditioner'
            name: Run Mode
          - entity: sensor.aircon_temperature
            name: Temperature
        show_name: false
      - type: glance
        title: Doorbell
        entities:
          - entity: sensor.ring_last_ding
            icon: 'mdi:bell-ring'
            name: Last Ring
          - entity: sensor.ring_last_motion
            icon: 'mdi:motion-sensor'
            name: Last Motion
      - entities:
          - entity: sensor.sems_status
            icon: 'mdi:power'
            name: Status
          - entity: sensor.sems_capacity
            icon: 'mdi:battery'
            name: Capacity
          - entity: sensor.sems_output_power
            icon: 'mdi:flash'
            name: Current Output Power
          - entity: sensor.sems_today_generated
            icon: 'mdi:solar-power'
            name: Electricity Generated Today
          - entity: sensor.sems_total_generated
            icon: 'mdi:all-inclusive'
            name: Total Electricity Generated
          - entity: sensor.sems_inner_temperature
            name: Inner Temperature
        show_header_toggle: false
        title: Solar Panels
        type: entities
    badges: []
    title: Home Status
  - cards:
      - type: vertical-stack
        cards:
          - type: entities
            title: Lights
            entities:
              - entity: light.theatre_room_left_lamp
              - entity: light.theatre_room_right_lamp
              - entity: light.fibaro_system_fgd212_dimmer_2_level_2
              - entity: light.fibaro_system_fgd212_dimmer_2_level_4
            show_header_toggle: true
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.fibaro_system_fgd212_dimmer_2_level_2
              - type: light
                entity: light.fibaro_system_fgd212_dimmer_2_level_4
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.theatre_room_left_lamp
              - type: light
                entity: light.theatre_room_right_lamp
          - type: entity-button
            entity: script.set_movie_lighting
            hold_action:
              action: none
            icon: 'mdi:theater'
            icon_height: 60px
            name: Movie Lights
            show_icon: true
            show_name: true
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.set_movie_lighting
      - cards:
          - entities:
              - entity: switch.aircon_on_off
                icon: 'mdi:power'
                name: Aircon On/Off
              - entity: input_select.aircon_run_mode
              - entity: sensor.aircon_temperature
                name: Aircon Temperature
              - entity: input_number.aircon_temperature
                icon: 'mdi:temperature-celsius'
                name: Set Temperature
            show_header_toggle: false
            title: Aircon Control
            type: entities
          - card:
              cards:
                - entities:
                    - entity: input_number.aircon_countdown_timer
                      icon: 'mdi:timer-sand'
                  show_header_toggle: false
                  title: Countdown To Off
                  type: entities
                - cards:
                    - entity: sensor.aircon_countdown_timer
                      hold_action:
                        action: none
                      icon: 'mdi:clock-outline'
                      name: 30 Minutes
                      show_icon: true
                      show_name: true
                      tap_action:
                        action: call-service
                        service: input_number.set_value
                        service_data:
                          entity_id: input_number.aircon_countdown_timer
                          value: 30
                      type: entity-button
                    - entity: sensor.aircon_countdown_timer
                      hold_action:
                        action: none
                      icon: 'mdi:clock-outline'
                      name: 1 Hour
                      show_icon: true
                      show_name: true
                      tap_action:
                        action: call-service
                        service: input_number.set_value
                        service_data:
                          entity_id: input_number.aircon_countdown_timer
                          value: 60
                      type: entity-button
                    - entity: sensor.aircon_countdown_timer
                      hold_action:
                        action: none
                      icon: 'mdi:clock-outline'
                      name: 1.5 Hours
                      show_icon: true
                      show_name: true
                      tap_action:
                        action: call-service
                        service: input_number.set_value
                        service_data:
                          entity_id: input_number.aircon_countdown_timer
                          value: 90
                      type: entity-button
                    - entity: sensor.aircon_countdown_timer
                      hold_action:
                        action: none
                      icon: 'mdi:clock-outline'
                      name: 2 Hours
                      show_icon: true
                      show_name: true
                      tap_action:
                        action: call-service
                        service: input_number.set_value
                        service_data:
                          entity_id: input_number.aircon_countdown_timer
                          value: 120
                      type: entity-button
                  type: horizontal-stack
              type: vertical-stack
            conditions:
              - entity: switch.aircon_on_off
                state: 'on'
            type: conditional
          - entities:
              - entity: switch.aircon_zone_living
                icon: 'mdi:air-filter'
                name: Living Area
              - entity: switch.aircon_zone_theatre
                icon: 'mdi:air-filter'
                name: Theatre
              - entity: switch.aircon_zone_master
                icon: 'mdi:air-filter'
                name: Master Bedroom
              - entity: switch.aircon_zone_bed23
                icon: 'mdi:air-filter'
                name: Bedroom 2 & 3
            show_header_toggle: false
            title: Aircon Zones
            type: entities
          - cards:
              - entity: script.aircon_warm_master
                hold_action:
                  action: none
                icon: 'mdi:home-automation'
                icon_height: 60px
                name: Cold Morning
                show_icon: true
                show_name: true
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.aircon_warm_master
                type: entity-button
              - entity: script.aircon_warm_master
                hold_action:
                  action: none
                icon: 'mdi:home-automation'
                icon_height: 60px
                name: Cold Night
                show_icon: true
                show_name: true
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.aircon_warm_master
                type: entity-button
            type: horizontal-stack
          - cards:
              - entity: script.aircon_fan_master
                hold_action:
                  action: none
                icon: 'mdi:home-automation'
                icon_height: 60px
                name: Sleeping Fan
                show_icon: true
                show_name: true
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.aircon_fan_master
                type: entity-button
              - entity: script.aircon_cool_central_living
                hold_action:
                  action: none
                icon: 'mdi:home-automation'
                icon_height: 60px
                name: Cool Centre
                show_icon: true
                show_name: true
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.aircon_cool_central_living
                type: entity-button
            type: horizontal-stack
        title: Aircon
        type: vertical-stack
      - type: vertical-stack
        cards:
          - entity: alarm_control_panel.alarm_com
            name: House Alarm
            states:
              - arm_home
              - arm_away
            type: alarm-panel
          - type: entities
            title: Garage Door
            show_header_toggle: false
            entities:
              - entity: >-
                  cover.aeon_labs_zw062_garage_door_controller_barrier_state_label
    badges:
      - person.michael
      - person.laura
      - sensor.yr_symbol
      - sun.sun
    path: default_view
    title: Home Control
  - badges: []
    cards:
      - entities:
          - artwork: cover
            entity: media_player.all_rooms
            group: true
            info: scroll
            source: icon
            type: 'custom:mini-media-player'
          - entity: media_player.kitchen_google_home_hub
            group: true
            hide:
              controls: true
            type: 'custom:mini-media-player'
          - entity: media_player.master_bedroom_speaker
            group: true
            hide:
              controls: true
            name: Master Bedroom Google Home
            type: 'custom:mini-media-player'
          - entity: media_player.office_google_home
            group: true
            hide:
              controls: true
            type: 'custom:mini-media-player'
          - entity: media_player.office_pc_speakers
            group: true
            hide:
              controls: true
            type: 'custom:mini-media-player'
          - entity: media_player.theatre_room_google_home
            group: true
            hide:
              controls: true
            type: 'custom:mini-media-player'
        show_header_toggle: false
        title: Music Players
        type: entities
      - entities:
          - artwork: full-cover
            entity: media_player.theatre_room_tv
            hide:
              mute: true
              power_state: false
            icon: 'mdi:television'
            info: short
            name: LG TV
            type: 'custom:mini-media-player'
          - artwork: full-cover
            entity: media_player.theatre_room_chromecast
            hide:
              mute: true
              power_state: false
            info: short
            name: Chromecast
            type: 'custom:mini-media-player'
        show_header_toggle: false
        title: Theatre Room TV
        type: entities
      - entities:
          - artwork: full-cover
            entity: media_player.living_room_chromecast
            hide:
              mute: true
              power_state: false
            info: short
            name: Chromecast
            type: 'custom:mini-media-player'
        show_header_toggle: false
        title: Living Room TV
        type: entities
    title: Media
