- platform: template
  scan_interval: 10
  sensors:
    front_door: #front door open/closed sensor
      friendly_name: "Front Door"
      value_template: >-
        {% if state_attr('alarm_control_panel.alarm_com', 'sensor_status')|regex_search('Front Door is Open', ignorecase=TRUE) %}
          Open
        {% else %}
          Closed
        {% endif %}
    motion_sensor_living: #living room motion sensor
      friendly_name: "Living Room Motion"
      value_template: >-
        {% if state_attr('alarm_control_panel.alarm_com', 'sensor_status')|regex_search('Living Sensor is Activated', ignorecase=TRUE) %}
          Active
        {% else %}
          Inactive
        {% endif %}
    motion_sensor_master_bedroom: #master bedroom motion sensor
      friendly_name: "Master Bedroom Motion"
      value_template: >-
        {% if state_attr('alarm_control_panel.alarm_com', 'sensor_status')|regex_search('Master Bedroom Sensor is Activated', ignorecase=TRUE) %}
          Active
        {% else %}
          Inactive
        {% endif %}
    motion_sensor_entry_hall: #entry hall motion sensor
      friendly_name: "Entry Hall Motion"
      value_template: >-
        {% if state_attr('alarm_control_panel.alarm_com', 'sensor_status')|regex_search('Entry Sensor is Open', ignorecase=TRUE) %}
          Active
        {% else %}
          Inactive
        {% endif %}

# Home Away Status
- platform: template
  sensors:
    away_from_home_state_validity:
      friendly_name: "House State Validity"
      value_template: >-
        {% if is_state("person.michael", "home") or is_state("person.laura", "home") -%}
          Someone Is Home
        {%- elif is_state("alarm_control_panel.alarm_com", "disarmed") -%}
          Alarm Disarmed
        {%- elif is_state("cover.aeon_labs_zw062_garage_door_controller_barrier_state_label", "open") -%}
          Garage Door Open
        {%- elif is_state("sensor.aircon_sensor", "on") -%}
          Aircon On
        {%- elif states | selectattr('entity_id', 'in', state_attr('group.televisions','entity_id')) | selectattr('state','ne','off') | list | length != 0 -%}
          Television On
        {%- elif states | selectattr('entity_id', 'in', state_attr('group.speakers','entity_id')) | selectattr('state','ne','off') | list | length != 0 -%}
          Speaker Left On
        {%- else -%}
          Valid State
        {%- endif %}
          
  