# Weather prediction
- platform: yr

# Ring Doorbell status updates (eg. wifi signal strength)
- platform: ring
- platform: template
  sensors:
    ring_last_ding:
      value_template: '{{ as_timestamp(states.sensor.ring_front_door_last_ding.attributes["created_at"]) | timestamp_custom("%I:%M:%S%p, %a %d %B %Y", True) }}'
    ring_last_motion:
      value_template: '{{ as_timestamp(states.sensor.ring_front_door_last_motion.attributes["created_at"]) | timestamp_custom("%I:%M:%S%p, %a %d %B %Y", True) }}'


# Aircon State Sensor
- platform: rest
  resource: http://192.168.1.106:2025/getSystemData
  name: aircon_sensor
  value_template: '{{ value_json.aircons.ac1.info.state }}'
  scan_interval: 5
  json_attributes:
    - aircons

- platform: template
  sensors:
    aircon_zone_living: #aircon zone z01
      value_template: '{{ states.sensor.aircon_sensor.attributes["aircons"]["ac1"]["zones"]["z01"]["state"] }}'
    aircon_zone_theatre: #aircon zone z02
      value_template: '{{ states.sensor.aircon_sensor.attributes["aircons"]["ac1"]["zones"]["z02"]["state"] }}'
    aircon_zone_master: #aircon zone z03
      value_template: '{{ states.sensor.aircon_sensor.attributes["aircons"]["ac1"]["zones"]["z03"]["state"] }}'
    aircon_zone_bed23: #aircon zone z04
      value_template: '{{ states.sensor.aircon_sensor.attributes["aircons"]["ac1"]["zones"]["z04"]["state"] }}'
    aircon_temperature: #aircon current temperature
      value_template: '{{ states.sensor.aircon_sensor.attributes["aircons"]["ac1"]["info"]["setTemp"] }}'
      device_class: temperature
      unit_of_measurement: '°C'
    aircon_run_mode: #aircon fan mode sensor
      value_template: '{{ states.sensor.aircon_sensor.attributes["aircons"]["ac1"]["info"]["mode"] }}'
    aircon_countdown_timer: #minutes before turning off
      value_template: '{{ states.sensor.aircon_sensor.attributes["aircons"]["ac1"]["info"]["countDownToOff"] }}'

- platform: template
  sensors:
    front_door: #front door open/closed sensor
      friendly_name: "Front Door"
      value_template: >-
        {% if state_attr('alarm_control_panel.alarm_com', 'sensor_status')|regex_search('Front Door is Open', ignorecase=TRUE) %}
          open
        {% else %}
          closed
        {% endif %}
        
        
        
# BOM Weather Sensor
- platform: bom_forecast
  product_id: IDW12300
  name: Perth Weather
  forecast_days: 6
  rest_of_today: TRUE
  friendly: TRUE
  friendly_state_format: '{max}, {summary}'
  monitored_conditions:
    - 'max'
    - 'min'
    - 'chance_of_rain'
    - 'possible_rainfall'
    - 'summary'
    - 'detailed_summary'
    
    
# Solar Panels
- platform: sems
  username: !secret sems_username
  password: !secret sems_password
  scan_interval: 60
- platform: template
  sensors:
    sems_name:
      friendly_name: "Solar Panel - Name"
      value_template: '{{ states.sensor.sems_portal.attributes["name"] }}'
    sems_capacity:
      friendly_name: "Solar Panel - Capacity"
      value_template: '{{ states.sensor.sems_portal.attributes["capacity"] }}'
      unit_of_measurement: "kW"
    sems_output_power:
      friendly_name: "Solar Panel - Current Output Power"
      value_template: '{{ states.sensor.sems_portal.attributes["outputpower"] }}'
      unit_of_measurement: "W"
    sems_inner_temperature:
      friendly_name: "Solar Panel - Inner Temperature"
      value_template: '{{ states.sensor.sems_portal.attributes["tempperature"] }}'
      unit_of_measurement: "°C"
    sems_total_generated: 
      friendly_name: "Solar Panel - Total Electricity Generated"
      value_template: '{{ states.sensor.sems_portal.attributes["etotal"] }}'     
      unit_of_measurement: "kWh"
    sems_today_generated: 
      friendly_name: "Solar Panel - Electricity Generated Today"
      value_template: '{{ states.sensor.sems_portal.attributes["eday"] }}'     
      unit_of_measurement: "kWh"
    sems_status: 
      friendly_name: "Solar Panel - Status"
      value_template: >-
        {% if is_state_attr("sensor.sems_portal", "status", -1) -%}
          Offline
        {%- else -%}
          Online
        {%- endif %}