############## AIRCON ##############

- platform: template
  switches:
  
    aircon_on_off: #overall aircon control
      value_template: "{{ is_state('sensor.aircon_sensor', 'on') }}"
      turn_on:
        service: rest_command.aircon_control
        data:
          #when turning on, set the countdown timer to 0
          command: '{"ac1":{"info":{"state":"on","countDownToOff": 0}}}'
      turn_off:
        service: rest_command.aircon_control
        data:
          command: '{"ac1":{"info":{"state":"off"}}}'
          
    aircon_zone_living: #zone z01
      value_template: "{{ is_state('sensor.aircon_zone_living', 'open') }}"
      turn_on:
        service: rest_command.aircon_control
        data:
          command: '{"ac1":{"zones":{"z01":{"state":"open"}}}}'
      turn_off:
        service: rest_command.aircon_control
        data:
          command: '{"ac1":{"zones":{"z01":{"state":"close"}}}}'
          
    aircon_zone_theatre: #zone z02
      value_template: "{{ is_state('sensor.aircon_zone_theatre', 'open') }}"
      turn_on:
        service: rest_command.aircon_control
        data:
          command: '{"ac1":{"zones":{"z02":{"state":"open"}}}}'
      turn_off:
        service: rest_command.aircon_control
        data:
          command: '{"ac1":{"zones":{"z02":{"state":"close"}}}}'      
          
    aircon_zone_master: #zone z03
      value_template: "{{ is_state('sensor.aircon_zone_master', 'open') }}"
      turn_on:
        service: rest_command.aircon_control
        data:
          command: '{"ac1":{"zones":{"z03":{"state":"open"}}}}'
      turn_off:
        service: rest_command.aircon_control
        data:
          command: '{"ac1":{"zones":{"z03":{"state":"close"}}}}'  
     
    aircon_zone_bed23: #zone z04
      value_template: "{{ is_state('sensor.aircon_zone_bed23', 'open') }}"
      turn_on:
        service: rest_command.aircon_control
        data:
          command: '{"ac1":{"zones":{"z04":{"state":"open"}}}}'
      turn_off:
        service: rest_command.aircon_control
        data:
          command: '{"ac1":{"zones":{"z04":{"state":"close"}}}}'

############## AIRCON ##############
