############## AIRCON ##############

- platform: template
  switches:
  
    aircon_on_off: #overall aircon control
      value_template: "{{ is_state('sensor.aircon_sensor', 'on') }}"
      turn_on:
        service: rest_command.aircon_control
        data:
          #when turning on, set the countdown timer to 0
          command: '{"ac1":{"info":{"state":"on","countDownToOff": 0}}}'
      turn_off:
        service: rest_command.aircon_control
        data:
          command: '{"ac1":{"info":{"state":"off"}}}'
          
    aircon_zone_living: #zone z01
      value_template: "{{ is_state('sensor.aircon_zone_living', 'open') }}"
      turn_on:
        service: rest_command.aircon_control
        data:
          command: '{"ac1":{"zones":{"z01":{"state":"open"}}}}'
      turn_off:
        service: rest_command.aircon_control
        data:
          command: '{"ac1":{"zones":{"z01":{"state":"close"}}}}'
          
    aircon_zone_theatre: #zone z02
      value_template: "{{ is_state('sensor.aircon_zone_theatre', 'open') }}"
      turn_on:
        service: rest_command.aircon_control
        data:
          command: '{"ac1":{"zones":{"z02":{"state":"open"}}}}'
      turn_off:
        service: rest_command.aircon_control
        data:
          command: '{"ac1":{"zones":{"z02":{"state":"close"}}}}'      
          
    aircon_zone_master: #zone z03
      value_template: "{{ is_state('sensor.aircon_zone_master', 'open') }}"
      turn_on:
        service: rest_command.aircon_control
        data:
          command: '{"ac1":{"zones":{"z03":{"state":"open"}}}}'
      turn_off:
        service: rest_command.aircon_control
        data:
          command: '{"ac1":{"zones":{"z03":{"state":"close"}}}}'  
     
    aircon_zone_bed23: #zone z04
      value_template: "{{ is_state('sensor.aircon_zone_bed23', 'open') }}"
      turn_on:
        service: rest_command.aircon_control
        data:
          command: '{"ac1":{"zones":{"z04":{"state":"open"}}}}'
      turn_off:
        service: rest_command.aircon_control
        data:
          command: '{"ac1":{"zones":{"z04":{"state":"close"}}}}'

############## AIRCON ##############

- platform: broadlink
  host: 192.168.1.14
  mac: '34:ea:34:99:eb:42'
  type: rm
  switches:
    roomba:
      friendly_name: "Roomba"
      command_on: 'JgD8AGEgIV8gXyBfXCIhXyBfIAACoGIfIGAfYB9gXSIfYR5hHgACol8iHmIdYh1iXCIfYR5hHgACo2EgHmEfYR1iXCIeYh1iHQACq2AhH2EeYR9gXCMfYB9gHwAComAhH2AfYR9gXCIgYB9gHwACoWAiH2AfYB9gXCMfYB9hHgAComAhH2EeYR5hXCIgYCBfIAACoGEgIGAfYB9gXSIfYR5hHgACql8jHWIdYh1iXCMeYR5hHgACo18iHmEeYh1iXCIeYh1iHQACo18jHWIdYh5hXSIeYh1iHQACo18jHWIdYh1iXCIfYR5hHgACq18iHmEeYh1iXCIeYh1iHgANBQAAAAAAAAAAAAAAAA=='
      command_off: 'JgCQAGAhHmIfYB9gH2BdIh5iXAACbGAhHmIeYR5hH2BdIh5iXAACZGAhHmIeYR5hH2BdIh5iXAACZGEhH2AfYB9gIF9eISBgXgACYl8iIGAfYB9gH2BfICBgXgACamEhH2AfYB9gH2BfICBgXgACYmEgIGAfYCBfIF9cIx9hXAACZGAhHmIeYR5hH2BdIh5iXAANBQAAAAAAAAAA'