sensor.away_from_home_state_validity:
  custom_ui_state_card: state-card-custom-ui
  icon: mdi:shield-home
  templates:
    hs_color: >
      if (state === 'Valid State' || state === 'Someone Is Home') return [121,100];
      else return [0,100];
    brightness: >
      if (state === 'Valid State' || state === 'Someone Is Home') return 23;
      else return 50;

#FIXME: Remove when ZHA covers are supported
light.axis_gear_00144dc3_1:
  friendly_name: Theatre Room Blinds
  icon_color: white
  templates:
    icon: >
      if (attributes.brightness > 50) return 'mdi:window-shutter-open';
      else return 'mdi:window-shutter';