ios:
  
# Push Notifications  
notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key

zone:
  - name: Laura's Work
    latitude: !secret zone_laura_work_latitude
    longitude: !secret zone_laura_work_longitude
    radius: 600
    icon: mdi:briefcase

  - name: Michael's Work
    latitude: !secret zone_michael_work_latitude
    longitude: !secret zone_michael_work_longitude
    radius: 120
    icon: mdi:briefcase

  # This will override the default home zone
  - name: Home
    latitude: !secret zone_home_latitude
    longitude: !secret zone_home_longitude
    radius: 220
    icon: mdi:home

automation:
  - alias: Notify Michael If Laura Leaving Work
    trigger:
      platform: zone
      entity_id: device_tracker.lauras_iphone
      zone: zone.laura_s_work
      event: leave
    action:
      - service: notify.pushbullet
        data:
          message: Laura is leaving work.

    
# Michael's Location          
#- platform: google_geocode
#  name: michael_location
#  origin: device_tracker.michael_michaelgalaxys10_2
#  options: street_number, street, city
#  display_zone: show
#  api_key: !secret google_maps_api_key
      
# Laura's Location          
#- platform: google_geocode
#  name: laura_location
#  origin: device_tracker.lauras_iphone
#  options: street_number, street, city
#  display_zone: show
#  api_key: !secret google_maps_api_key
