
# RING DOORBELL
ring:
  username: !secret ring_username
  password: !secret ring_password

# Ring Doorbell status updates (eg. wifi signal strength)
sensor:
  - platform: ring
  - platform: template
    sensors:
      ring_last_ding:
        value_template: '{{ as_timestamp(states.sensor.ring_front_door_last_ding.attributes["created_at"]) | timestamp_custom("%I:%M:%S%p, %a %d %B %Y", True) }}'
      ring_last_motion:
        value_template: '{{ as_timestamp(states.sensor.ring_front_door_last_motion.attributes["created_at"]) | timestamp_custom("%I:%M:%S%p, %a %d %B %Y", True) }}'

